{
 "title": "ForeScale",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "스케일아웃 트리거 (0=정상 / 1=발동)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "forescale_any_trigger{job=\"forescale\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prophet 트래픽 예측값 (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "forescale_pred_traffic{job=\"forescale\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prophet CPU 예측값 (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "forescale_pred_cpu{job=\"forescale\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네트워크 트래픽 유입량(bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 사용률(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}